-- CreateTable
CREATE TABLE `administrateur` (
    `IDADMIN` INTEGER NOT NULL AUTO_INCREMENT,
    `MATRICULEADMIN` VARCHAR(255) NOT NULL,
    `NOMADMIN` VARCHAR(255) NOT NULL,
    `PRENOMADMIN` VARCHAR(255) NOT NULL,
    `EMAILADMIN` VARCHAR(255) NOT NULL,
    `PASSWARDADMIN` VARCHAR(255) NOT NULL,
    `PHOTOADMIN` VARCHAR(255) NOT NULL,

    UNIQUE INDEX `MATRICULEADMIN`(`MATRICULEADMIN`),
    PRIMARY KEY (`IDADMIN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `affectation` (
    `IDADMIN` INTEGER NOT NULL,
    `IDENCADREUR` INTEGER NOT NULL,
    `IDDOSSIER` INTEGER NOT NULL,
    `IDSTRUCTURE` INTEGER NOT NULL,

    INDEX `FK_AFFECTATION_DOSSIER`(`IDDOSSIER`),
    INDEX `FK_AFFECTATION_ENCADREUR`(`IDENCADREUR`),
    INDEX `FK_AFFECTATION_STRUCTURE`(`IDSTRUCTURE`),
    PRIMARY KEY (`IDADMIN`, `IDENCADREUR`, `IDDOSSIER`, `IDSTRUCTURE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `dossier` (
    `IDDOSSIER` INTEGER NOT NULL AUTO_INCREMENT,
    `MATRICULEETUDIANT` VARCHAR(255) NULL,
    `DATEDEBUTDESEANCE` DATE NULL,
    `DATEFINDESEANCE` DATE NULL,
    `ETAT` TEXT NULL,
    `THEME` VARCHAR(500) NULL,
    `CNI` VARCHAR(255) NOT NULL,
    `CERTIFICAT` VARCHAR(255) NOT NULL,
    `LETTREMOTIVATION` VARCHAR(255) NOT NULL,
    `LETTRERECOMMENDATION` VARCHAR(255) NOT NULL,
    `PHOTOPROFIL` VARCHAR(255) NOT NULL,
    `DATEDEPOT` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `FK_DEPOSER`(`MATRICULEETUDIANT`),
    PRIMARY KEY (`IDDOSSIER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `encadreur` (
    `IDENCADREUR` INTEGER NOT NULL AUTO_INCREMENT,
    `MATRICULEENCADREUR` VARCHAR(255) NOT NULL,
    `NOMENCADREUR` VARCHAR(255) NULL,
    `PRENOMENCADREUR` VARCHAR(255) NULL,
    `IDSTRUCTURE` INTEGER NULL,
    `POSTE` VARCHAR(255) NULL,

    UNIQUE INDEX `MATRICULEENCADREUR`(`MATRICULEENCADREUR`),
    INDEX `IDSTRUCTURE`(`IDSTRUCTURE`),
    PRIMARY KEY (`IDENCADREUR`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etudiant` (
    `MATRICULEETUDIANT` VARCHAR(255) NOT NULL,
    `NOMETUDIANT` VARCHAR(255) NULL,
    `PRENOMETUDIANT` VARCHAR(255) NULL,
    `ETABLISSEMENT` VARCHAR(255) NULL,
    `VILLERESIDENCE` VARCHAR(255) NULL,
    `PARCOURS` VARCHAR(255) NULL,
    `NIVEAU` VARCHAR(255) NULL,
    `EMAIL` TEXT NOT NULL,
    `TEL` VARCHAR(255) NOT NULL,
    `FILIERE` VARCHAR(255) NOT NULL,
    `SEXE` TEXT NOT NULL,
    `DATE` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`MATRICULEETUDIANT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `logs_actions` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `user_email` VARCHAR(255) NULL,
    `user_name` VARCHAR(255) NULL,
    `action` VARCHAR(255) NULL,
    `methode_http` VARCHAR(10) NULL,
    `endpoint` VARCHAR(500) NULL,
    `requete_executee` TEXT NULL,
    `ip_address` VARCHAR(45) NULL,
    `user_agent` TEXT NULL,
    `status_code` INTEGER NULL,
    `horodatage` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `idx_action`(`action`),
    INDEX `idx_horodatage`(`horodatage`),
    INDEX `idx_user_email`(`user_email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `rapport` (
    `IDDOSSIER` INTEGER NOT NULL AUTO_INCREMENT,
    `MATRICULE` VARCHAR(30) NOT NULL,
    `COMMENTAIRE` VARCHAR(50) NOT NULL,
    `THEME` VARCHAR(255) NOT NULL,
    `FICHIER` VARCHAR(255) NOT NULL,
    `DATE` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `MATRICULE`(`MATRICULE`),
    PRIMARY KEY (`IDDOSSIER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `structures` (
    `IDSTRUCTURE` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMSTRUCTURE` VARCHAR(255) NOT NULL,
    `ABBREVIATION` VARCHAR(50) NOT NULL,
    `IDPARENT` INTEGER NULL,

    INDEX `IDPARENT`(`IDPARENT`),
    PRIMARY KEY (`IDSTRUCTURE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `affectation` ADD CONSTRAINT `affectation_ibfk_1` FOREIGN KEY (`IDADMIN`) REFERENCES `administrateur`(`IDADMIN`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `affectation` ADD CONSTRAINT `affectation_ibfk_2` FOREIGN KEY (`IDENCADREUR`) REFERENCES `encadreur`(`IDENCADREUR`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `affectation` ADD CONSTRAINT `affectation_ibfk_3` FOREIGN KEY (`IDDOSSIER`) REFERENCES `dossier`(`IDDOSSIER`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `affectation` ADD CONSTRAINT `affectation_ibfk_4` FOREIGN KEY (`IDSTRUCTURE`) REFERENCES `structures`(`IDSTRUCTURE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `dossier` ADD CONSTRAINT `dossier_ibfk_1` FOREIGN KEY (`MATRICULEETUDIANT`) REFERENCES `etudiant`(`MATRICULEETUDIANT`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `encadreur` ADD CONSTRAINT `encadreur_ibfk_1` FOREIGN KEY (`IDSTRUCTURE`) REFERENCES `structures`(`IDSTRUCTURE`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `rapport` ADD CONSTRAINT `rapport_ibfk_1` FOREIGN KEY (`MATRICULE`) REFERENCES `etudiant`(`MATRICULEETUDIANT`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `structures` ADD CONSTRAINT `structures_ibfk_1` FOREIGN KEY (`IDPARENT`) REFERENCES `structures`(`IDSTRUCTURE`) ON DELETE RESTRICT ON UPDATE RESTRICT;
