-- CreateTable
CREATE TABLE `lettreAcceptation` (
    `IDLETTRE` INTEGER NOT NULL AUTO_INCREMENT,
    `IDDOSSIER` INTEGER NOT NULL,
    `COMMENTAIRE` VARCHAR(500) NOT NULL,
    `FICHIER` VARCHAR(255) NOT NULL,
    `DATEUPLOAD` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `FK_LETTRE_ACCEPTATION_DOSSIER`(`IDDOSSIER`),
    PRIMARY KEY (`IDLETTRE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `lettreAcceptation` ADD CONSTRAINT `lettreAcceptation_IDDOSSIER_fkey` FOREIGN KEY (`IDDOSSIER`) REFERENCES `dossier`(`IDDOSSIER`) ON DELETE CASCADE ON UPDATE CASCADE;
